// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GamePacket
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CardData : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public CardData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short Rank { get { return __p.bb.GetShort(__p.bb_pos + 0); } }
  public short Suit { get { return __p.bb.GetShort(__p.bb_pos + 2); } }

  public static Offset<GamePacket.CardData> CreateCardData(FlatBufferBuilder builder, short Rank, short Suit) {
    builder.Prep(2, 4);
    builder.PutShort(Suit);
    builder.PutShort(Rank);
    return new Offset<GamePacket.CardData>(builder.Offset);
  }
}


}
